---
- name: Install WordPress, MariaDB, Nginx, and PHP-FPM
  hosts: all 
  remote_user: root
  # remote_user: user
  # sudo: yes

  roles:
    - common
    - { mariadb when: ansible_hostname=client2 } 
    - nginx
    - php-fpm
    - wordpress
